#!/usr/bin/env python3
"""
Rebuilds clex/cards.json and clex/decks.json from Moxfield + Scryfall.

Run:  py -3 clex/tools/build-data.py

You only need this when a decklist changes on Moxfield. The app itself never
calls the network: it reads the two JSON files this script writes, so it works
offline at the table.
"""
import urllib.request, json, time, os, sys

UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/126 Safari/537.36'
HJ = {'User-Agent': UA, 'Accept': 'application/json'}
HP = {'User-Agent': 'BigClexOptimizer/1.0', 'Accept': 'application/json',
      'Content-Type': 'application/json'}

DECKS = [
    {"id": "clex",   "moxfield": "Qnja5ftUk02C9cobAAH04g"},
    {"id": "krenko", "moxfield": "gJOfAVLX5nuAeyg8VIvX0w"},
]

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def get(url, headers=HJ, data=None, method=None):
    req = urllib.request.Request(url, headers=headers, data=data, method=method)
    return json.loads(urllib.request.urlopen(req, timeout=40).read())


def fetch_deck(mox_id):
    d = get('https://api2.moxfield.com/v3/decks/all/' + mox_id)
    boards = d.get('boards', {})

    def names(board):
        return [(v.get('quantity', 1), v['card']['name'])
                for v in boards.get(board, {}).get('cards', {}).values()]

    return {
        "name": d.get('name', mox_id),
        "url": d.get('publicUrl', ''),
        "commanders": names('commanders'),
        "main": names('mainboard'),
        "side": names('sideboard'),
    }


def fetch_cards(all_names):
    # Scryfall's collection endpoint wants the FRONT face name for double-faced
    # cards, but Moxfield hands back "Front // Back". Look up the front face and
    # remember the Moxfield spelling so the decklist still resolves.
    alias = {}
    lookup = set()
    for n in all_names:
        front = n.split(' // ')[0].strip()
        lookup.add(front)
        if front != n:
            alias[front] = n

    out, missing = {}, []
    names = sorted(lookup)
    for i in range(0, len(names), 75):
        chunk = names[i:i + 75]
        body = json.dumps({"identifiers": [{"name": n} for n in chunk]}).encode()
        d = get('https://api.scryfall.com/cards/collection', headers=HP,
                data=body, method='POST')
        missing += [nf.get('name') for nf in d.get('not_found', [])]
        for c in d.get('data', []):
            faces = c.get('card_faces')
            if faces and 'oracle_text' not in c:
                oracle = "\n//\n".join(f.get('oracle_text', '') for f in faces)
                mc = faces[0].get('mana_cost', '')
                pw = faces[0].get('power')
                tf = faces[0].get('toughness')
            else:
                oracle = c.get('oracle_text', '')
                mc = c.get('mana_cost', '')
                pw, tf = c.get('power'), c.get('toughness')
            key = alias.get(c['name'], c['name'])
            out[key] = {
                "n": key,
                "c": mc,
                "v": c.get('cmc', 0),
                "t": c.get('type_line', ''),
                "o": oracle,
                "ci": c.get('color_identity', []),
                "p": pw,
                "tf": tf,
                "pm": c.get('produced_mana'),
            }
        time.sleep(0.15)
    return out, missing


def main():
    decks = []
    pool = set()
    for spec in DECKS:
        d = fetch_deck(spec['moxfield'])
        d['id'] = spec['id']
        decks.append(d)
        for grp in ('commanders', 'main', 'side'):
            for _q, n in d[grp]:
                pool.add(n)
        print(f"deck {spec['id']}: {d['name']} "
              f"({len(d['main'])} main, {len(d['side'])} side)", file=sys.stderr)

    print(f"fetching {len(pool)} unique cards from Scryfall", file=sys.stderr)
    cards, missing = fetch_cards(pool)
    if missing:
        print("!! NOT FOUND ON SCRYFALL:", missing, file=sys.stderr)

    payload = {"source": "scryfall+moxfield", "count": len(cards),
               "cards": [cards[k] for k in sorted(cards)], "decks": decks}
    blob = json.dumps(payload, ensure_ascii=False, separators=(',', ':'))

    # Emitted as a plain script, not JSON, on purpose: fetch() of a local file
    # is blocked by CORS, and opening index.html straight from a folder has to
    # keep working. A <script src> has no such restriction.
    with open(os.path.join(HERE, 'data.js'), 'w', encoding='utf-8') as f:
        print('/* Generated by tools/build-data.py. Do not hand-edit. */', file=f)
        print('window.CLEX_DATA=' + blob + ';', file=f)

    print(f"wrote data.js ({len(cards)} cards, {len(decks)} decks)",
          file=sys.stderr)
    if missing:
        sys.exit(1)


if __name__ == '__main__':
    main()
